ALTER TABLE "grouped_purchase_orders"
  ADD COLUMN "note" VARCHAR(1000),
  ADD COLUMN "raw_material" VARCHAR(255),
  ADD COLUMN "category_type" VARCHAR(255),
  ADD COLUMN "category" VARCHAR(255),
  ADD COLUMN "sub_category" VARCHAR(255),
  ADD COLUMN "brand" VARCHAR(255),
  ADD COLUMN "total_required_qty" DECIMAL(12,2),
  ADD COLUMN "total_grouped_qty" DECIMAL(12,2),
  ADD COLUMN "no_of_styles" INTEGER,
  ADD COLUMN "stock_uom" VARCHAR(100),
  ADD COLUMN "buying_uom" VARCHAR(100),
  ADD COLUMN "convert_value" DECIMAL(12,4),
  ADD COLUMN "round_of" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "buying_qty" DECIMAL(12,4),
  ADD COLUMN "buying_qty_round" DECIMAL(12,4),
  ADD COLUMN "difference_round" DECIMAL(12,4),
  ADD COLUMN "moq_stock_uom" DECIMAL(12,4),
  ADD COLUMN "moq_buying" DECIMAL(12,4),
  ADD COLUMN "extra_buying_uom" DECIMAL(12,4),
  ADD COLUMN "buying_qty_total" DECIMAL(12,4),
  ADD COLUMN "vendor_price" DECIMAL(12,4),
  ADD COLUMN "vendor_price_inr" DECIMAL(12,4),
  ADD COLUMN "other_charges" DECIMAL(12,4),
  ADD COLUMN "other_charges_inr" DECIMAL(12,4),
  ADD COLUMN "currency" VARCHAR(100),
  ADD COLUMN "exchange_price" DECIMAL(12,4);

ALTER TABLE "grouped_purchase_order_lines"
  ADD COLUMN "category_type" VARCHAR(255),
  ADD COLUMN "internal_price_bom" DECIMAL(12,4),
  ADD COLUMN "other_charges_per_item" DECIMAL(12,4),
  ADD COLUMN "total_extra" DECIMAL(12,4),
  ADD COLUMN "total_spend" DECIMAL(12,4);