import { createMaster, lookup, text } from "@/lib/master-data/master-data-models";

export const MERCHANDISING_MASTER_DEFINITIONS = [
  createMaster("entity", "Entity", "Company and legal entity names.", [text("entity_name", "Entity Name", { required: true, unique: true })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 1 }),
  createMaster("category", "Category", "Primary product category master.", [lookup("Category_Type_Master", "Category Type Master", "category-type", { required: true }), text("Category_Name", "Category Name", { required: true, unique: true }), text("Maximum_Excess_Allowed", "Maximum Excess Allowed", { type: "percentage" }), text("Create_Cost_Center", "Create Cost Center", { type: "checkbox" })], { labelField: "Category_Name", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 2 }),
  createMaster("sub-category", "Sub Category", "Child category values linked to category.", [lookup("category", "Category", "category", { required: true }), text("sub_category", "Sub Category", { required: true, unique: true })], { labelField: "sub_category", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 3 }),
  createMaster("brand", "Brand", "Brand or label master.", [text("Brand", "Brand", { required: true, unique: true }), text("Maximum_Allowed_Excess", "Maximum Allowed Excess", { type: "percentage" }), text("Auto_add_Excess_to_RM", "Auto add Excess to RM", { type: "checkbox" }), lookup("Pre_Order_Checklist1", "Pre Order Checklist", "pre-order-checklist")], { labelField: "Brand", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 4 }),
  createMaster("buyer", "Buyer", "Buyer and customer master.", [text("Buyer_Name", "Buyer Name", { required: true, unique: true }), text("Buyer_Email", "Buyer Email", { type: "text" }), lookup("Currency_Type", "Currency Type", "currency-type")], { labelField: "Buyer_Name", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 5 }),
  createMaster("season", "Season", "Season and campaign master.", [text("season", "Season", { required: true, unique: true })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 6 }),
  createMaster("article", "Article", "Design and production master for articles and styles.", [
    text("article", "Article Name", { required: true, unique: true }),
    text("article_code", "Article Code", { readOnly: true }),
    text("design_by", "Design By"),
    text("designed_date", "Designed Date", { type: "date" }),
    text("running_order_qty", "Running Order Qty", { type: "number", readOnly: true }),
    text("running_order_variants", "Running Order Variants", { type: "number", readOnly: true }),
  ], { labelField: "article", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 7 }),
  createMaster("color", "Color", "Color and shade master.", [text("Colors", "Colors", { required: true, unique: true })], { labelField: "Colors", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 8 }),
  createMaster("size-group", "Size Group", "Grouped size families with their mapped sizes.", [lookup("Brand1", "Brand", "brand", { required: true }), text("Size_Group", "Size Group", { required: true, unique: true }), lookup("Measurement_Chart1", "Measurement Chart", "measurement-chart"), lookup("Size", "Sizes", "size", { multiple: true, required: true })], { labelField: "Size_Group", moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 9 }),
  createMaster("size", "Size", "Reusable size values mapped to groups from the Size Group master.", [text("Size", "Size", { required: true, unique: true })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 10 }),
  createMaster("category-type", "Category Type", "Category type lookup values.", [text("Category_Type1", "Category Type", { required: true, unique: true }), text("Books_Item_ID", "Books Item ID")], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 11 }),
  createMaster("measurement-chart", "Measurement Chart", "Measurement chart lookup values.", [text("Measurement_Chart", "Measurement Chart", { required: true, unique: true })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 12 }),
  createMaster("pre-order-checklist", "Pre Order Checklist", "Pre-order checklist lookup values.", [text("Pre_Order_Checklist", "Pre Order Checklist", { required: true, unique: true })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 13 }),
  createMaster("merchandiser", "Merchandiser", "User and merchandiser assignment master.", [text("merchandiser", "Merchandiser", { required: true })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 14 }),
  createMaster("order-volume", "Order Volume", "Order volume classifications.", [text("Order_Volume", "Order Volume", { required: true }), text("From", "From", { type: "number" }), text("To", "To", { type: "number" })], { moduleGroup: "order-management", moduleSubGroup: "merchandising", moduleOrder: 15 }),
];
